services:
  observant:
    build:
      args:
        SWIFT_SDKS: |-
          c701d3f5bb69464fd443f20c4748cab068c9c6d8f6995f1ba5be70022778d21f https://download.swift.org/swift-6.1-branch/static-sdk/swift-6.1-DEVELOPMENT-SNAPSHOT-2025-03-12-a/swift-6.1-DEVELOPMENT-SNAPSHOT-2025-03-12-a_static-linux-0.0.1.artifactbundle.tar.gz
          97b6269aee3baa07867e3dcbce2536d413f8a426c2a54862f23cc97a95ac1bb9 https://github.com/swiftwasm/swift/releases/download/swift-wasm-6.1-SNAPSHOT-2025-03-20-a/swift-wasm-6.1-SNAPSHOT-2025-03-20-a-wasm32-unknown-wasi.artifactbundle.zip
        # DOCKER_IMAGE: swift
        SWIFT_WEBROOT: https://download.swift.org/swift-6.1-branch
      context: .
      dockerfile: Dockerfile
      secrets:
        - github_token
      target: production
    environment:
      - ATTACHMENT_EXTENSION_TO_TREAT_AS_INPUT=.swift
      - DISCORD_NICKNAME
      - DISCORD_PLAYING
      - DISCORD_TOKEN
      - ENV_ARGS
      - ENV_COMMAND
      - GITHUB_TOKEN
      - NUMBER_OF_LINES_TO_EMBED_OUTPUT
      - NUMBER_OF_LINES_TO_EMBED_UPLOADED_OUTPUT
      - PORT=8081
      - TARGET_ARGS_TO_USE_STDIN
      - TARGET_CLI
      - TARGET_DEFAULT_ARGS
      - TIMEOUT_ARGS=--signal=KILL 120
      - TIMEOUT_COMMAND
    tty: true
    ports:
      - "8081:8081"
secrets:
  github_token:
    file: .github_token
