services:
  observant:
    build:
      args:
        DOCKER_IMAGE: swift
        SWIFT_WEBROOT: https://download.swift.org/development
        USE_SNAPSHOT: false
        USE_SWIFT_SDKS: true
      platforms:
        - linux/amd64
        - linux/arm64
      context: .
      dockerfile: Dockerfile
      secrets:
        - github_token
      target: production
    environment:
      - ATTACHMENT_EXTENSION_TO_TREAT_AS_INPUT=.swift
      - DISCORD_NICKNAME
      - DISCORD_PLAYING
      - DISCORD_TOKEN
      - ENV_ARGS
      - ENV_COMMAND
      - GITHUB_TOKEN
      - NUMBER_OF_LINES_TO_EMBED_OUTPUT
      - NUMBER_OF_LINES_TO_EMBED_UPLOADED_OUTPUT
      - TARGET_ARGS_TO_USE_STDIN
      - TARGET_CLI
      - TARGET_DEFAULT_ARGS
      - TIMEOUT_ARGS=--signal=KILL 120
      - TIMEOUT_COMMAND
    tty: true
secrets:
  github_token:
    file: .github_token
