services:
  observant:
    build:
      args:
        SWIFT_SDKS: |-
          cd1b0de0bcc809692e803a078800b9d577c0eefbd2b3d2cfd24e53f019ca5de3 https://download.swift.org/development/static-sdk/swift-DEVELOPMENT-SNAPSHOT-2025-01-31-a/swift-DEVELOPMENT-SNAPSHOT-2025-01-31-a_static-linux-0.0.1.artifactbundle.tar.gz
          2a8a1faed05b7d5b4e8b5b489261d950bb06e5e0f6ce1713733acd6d71701c6b https://github.com/swiftwasm/swift/releases/download/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-03-17-a/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-03-17-a-wasm32-unknown-wasi.artifactbundle.zip
        # DOCKER_IMAGE: swift
        SWIFT_WEBROOT: https://download.swift.org/development
      context: .
      dockerfile: Dockerfile
      secrets:
        - github_token
      target: production
    environment:
      - ATTACHMENT_EXTENSION_TO_TREAT_AS_INPUT=.swift
      - DISCORD_NICKNAME
      - DISCORD_PLAYING
      - DISCORD_TOKEN
      - ENV_ARGS
      - ENV_COMMAND
      - GITHUB_TOKEN
      - NUMBER_OF_LINES_TO_EMBED_OUTPUT
      - NUMBER_OF_LINES_TO_EMBED_UPLOADED_OUTPUT
      - PORT=8081
      - TARGET_ARGS_TO_USE_STDIN
      - TARGET_CLI
      - TARGET_DEFAULT_ARGS
      - TIMEOUT_ARGS=--signal=KILL 120
      - TIMEOUT_COMMAND
    tty: true
    ports:
      - "8081:8081"
secrets:
  github_token:
    file: .github_token
