services:
  - type: web
    name: swift_discord_bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      # build time args
      - key: DOCKER_IMAGE
        value: swift
      - key: SWIFT_WEBROOT
        value: https://download.swift.org/development
      - key: USE_SNAPSHOT
        value: false
      - key: USE_SWIFT_SDKS
        value: true
      # runtime environment variables
      - key: DISCORD_NICKNAME
        sync: false
      - key: DISCORD_PLAYING
        sync: false
      - key: DISCORD_TOKEN
        sync: false
      - key: GITHUB_TOKEN
        sync: false
    autoDeploy: false
