services:
  - type: web
    name: swiftmain-discord-bot
    env: docker
    region: ohio
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: DISCORD_NICKNAME
        value: swift-main
      - key: DISCORD_PLAYING
        sync: false
      - key: DISCORD_TOKEN
        sync: false
      - key: DOCKER_IMAGE
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: SWIFT_WEBROOT
        value: https://download.swift.org/development
    autoDeploy: false
