services:
  - type: web
    name: swiftmain-discord-bot
    env: docker
    region: ohio
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: DISCORD_NICKNAME
        value: swift-main
      - key: DISCORD_PLAYING
        sync: false
      - key: DISCORD_TOKEN
        sync: false
      - key: DOCKER_IMAGE
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: SWIFT_SDKS
        value: |-
          cd1b0de0bcc809692e803a078800b9d577c0eefbd2b3d2cfd24e53f019ca5de3 https://download.swift.org/development/static-sdk/swift-DEVELOPMENT-SNAPSHOT-2025-01-31-a/swift-DEVELOPMENT-SNAPSHOT-2025-01-31-a_static-linux-0.0.1.artifactbundle.tar.gz
          2a8a1faed05b7d5b4e8b5b489261d950bb06e5e0f6ce1713733acd6d71701c6b https://github.com/swiftwasm/swift/releases/download/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-03-17-a/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-03-17-a-wasm32-unknown-wasi.artifactbundle.zip
      - key: SWIFT_WEBROOT
        value: https://download.swift.org/development
    autoDeploy: false
