#!/bin/bash -eu
[[ -n ${DEBUG:-} ]] && set -x
set -o pipefail

# print the error message and exit with status 1
function error_exit() {
	echo "$(basename "${1}"): Error: ${*:2}" >&2
	exit 1
}

[[ -x main ]] || error_exit "${0}" "main is not an executable file"

commands=()
while [[ ${1:-} == [^-]* ]]; do
	commands+=("${1}")
	shift
done

wasmkit-cli run main "$@"

# chain remaining commands
[[ ${#commands[@]} -eq 0 ]] || "swift-${commands[0]}" "${commands[@]:1}" "$@"
