#!/bin/bash -eu
. swift-bot-helper

if [[ ${1:-} == "--list-runtimes" ]]; then
	echo wasmkit-cli wasmtime wazero
	exit
fi

# shellcheck disable=SC2310
prepare_next_commands "$@" && shift ${#next_commands[@]}
# shellcheck disable=SC2310
if [[ ! -x main ]]; then
	prepend_next_commands wasi swiftc "${current_command}" && EXEC=1 call_next_commands "$@"
	error_exit "${0}" "main is not an executable file"
fi

set +e
case "${current_command}" in
exec-wasi|wasmkit-cli)
	call_command wasmkit-cli run main "$@"
	;;
wasmtime)
	call_command wasmtime main "$@"
	;;
wazero)
	call_command wazero run main "$@"
	;;
*)
	error_exit "${0}" "unexpected command: ${current_command}"
	;;
esac
# chain remaining commands
call_remaining_next_commands "$@"
status=$?
[[ ! -f main ]] || rm main
exit "${status}"
