#!/bin/bash -eu
. swift-bot-helper

prevent_recursive_execution "$@"
# shellcheck disable=SC2310
prepare_next_commands "$@" && shift ${#next_commands[@]}

# Check USE_SWIFT_TARGET_TRIPLE
# shellcheck disable=SC2310
prepare_swift_args_for_sdk_and_use_swiftc "$@" && set -- "${swift_args_for_sdk[@]}" "$@"

# Prepare swift-testing
prepare_swift_testing "$@"

# stop exporting USE_SWIFTC
export -n USE_SWIFTC

# split $@ by "--" and move the arguments before "--" to swiftc_flags
swiftc_flags=("$@")
set --
for i in "${!swiftc_flags[@]}" ""; do
	[[ -n ${i} && ${swiftc_flags[i]} == -- ]] && break
done && {
	set -- "${swiftc_flags[@]:i+1}"
	swiftc_flags=("${swiftc_flags[@]:0:i}")
}

# if $@ contains "-", move "-" to swiftc_flags
removing_hyphen=("$@")
for i in "${!removing_hyphen[@]}" ""; do
	[[ -n ${i} && ${removing_hyphen[i]} == "-" ]] && break
done && {
	swiftc_flags+=("-")
	set -- "${removing_hyphen[@]:0:i}" "${removing_hyphen[@]:i+1}"
}

# execute swiftc with swiftc_flags
call_command swiftc "${swiftc_flags[@]}"

# following commands are for the main executable file
call_next_commands "$@"
