#!/bin/bash -eu
. swift-bot-helper

target_triple=${1:-} darwin_platform_name=${2:-}
[[ -n ${target_triple} ]] || error_exit "${0}" "missing target_triple"

sdk_configuration=$(swift-sdk-configuration "${target_triple}")

# Detect deployment target from SDKSettings.json
sdk_root_path=$(jq -r '.sdkRootPath' <<<"${sdk_configuration}")
sdk_settings="${sdk_root_path}/SDKSettings.json"
[[ -f ${sdk_settings} ]] || error_exit "${0}" "SDKSettings.json not found in ${sdk_root_path}"
darwin_deployment_target=$(
	jq --raw-output --argjson darwin "{${darwin_platform_name:+\"platform_name\":\"${darwin_platform_name}\"}}" '
        ($darwin.platform_name // .DefaultProperties.PLATFORM_NAME) as $darwin_platform_name
        |.SupportedTargets[$darwin_platform_name].DefaultDeploymentTarget
    ' "${sdk_settings}"
) || error_exit "${0}" "Failed to get deployment target for ${darwin_platform_name}"
echo "${darwin_deployment_target}"
