#!/bin/bash -eu
. swift-bot-helper

target_triple=${1:-}
# ignore target_triple if it is "-"
[[ "${target_triple}" == "-" ]] && target_triple=""

swift_sdk_json_file_list=$(
	shopt -s nullglob
	info_json_files=(~/{.swiftpm,Library/org.swift.swiftpm}/swift-sdks/*/info.json)
	[[ -v info_json_files ]] || error_exit "${0}" "No swift-sdk info.json files found"
	jq --raw-output '
        .artifacts|map_values(.variants|map("\(input_filename|rtrimstr("info.json"))\(.path)/swift-sdk.json"))[][]
    ' ~/{.swiftpm,Library/org.swift.swiftpm}/swift-sdks/*/info.json
)
mapfile -t swift_sdk_json_files <<<"${swift_sdk_json_file_list}"
[[ -v swift_sdk_json_files ]] || error_exit "${0}" "sdk for ${target_triple} not found"

target_triple_to_sdk_configuration_json=$(
	jq '
        .targetTriples|map_values(.root = (input_filename|rtrimstr("swift-sdk.json")))
    ' "${swift_sdk_json_files[@]}" | jq --slurp --sort-keys 'reduce .[] as $item ({}; . + $item)'
)
sdk_configuration=$(
	jq --exit-status --raw-output --arg target_triple "${target_triple}" '
        map_values(
            .root as $root
            | (.sdkRootPath,.swiftResourcesPath,.swiftStaticResourcesPath|select(type == "string")) |= $root + .
            | (.includeSearchPaths,.librarySearchPaths,.toolsetPaths|select(type == "array")[]) |= $root + .
            | del(.root)
        )
        | if $target_triple|length != 0 then .[$target_triple] end
    ' <<<"${target_triple_to_sdk_configuration_json}"
) || error_exit "${0}" "Failed to get configuration for ${target_triple}"

echo "${sdk_configuration}"
