#!/bin/bash -eu
. swift-bot-helper

prevent_recursive_execution "$@"
# shellcheck disable=SC2310
prepare_next_commands "$@" && shift ${#next_commands[@]}

# shellcheck disable=SC2310
if has_ancestor swiftc; then
	[[ -x main ]] || exit 0 # error_exit "${0}" "main is not an executable file"
	file_info=$(file -b main)
	set +e
	case "${file_info}" in
	ELF*)
		call_command ./main "$@"
		status=$?
		[[ ! -f main ]] || rm main
		exit "${status}"
		;;
	WebAssembly*)
		prepend_next_commands exec-wasi
		call_next_commands "$@"
		status=$?
		[[ ! -f main ]] || rm main
		exit "${status}"
		;;
	*)
		echo "can not execute main: ${file_info}" >&2
		exit 1
		;;
	esac
else
	if [[ -v USE_SWIFTC ]]; then
		prepend_next_commands swiftc
		EXEC=1 call_next_commands "$@"
	else
		# Check USE_SWIFT_TARGET_TRIPLE
		# shellcheck disable=SC2310
		prepare_swift_args_for_sdk_and_use_swiftc "$@" && set -- "${swift_args_for_sdk[@]}" "$@"
		prepare_swift_testing "$@"
		call_command swift "$@"
	fi
fi
