name: Cleanup Registry
on:
  workflow_dispatch:
    inputs:
      delete-only-untagged-versions:
        description: 'Delete only untagged versions ( default: true )'
        required: false
        default: 'true'
      min-versions-to-keep:
        description: 'Minimum number of versions to keep ( default: 200 )'
        required: false
        default: '200'

permissions:
  contents: read
  packages: write

jobs:
  cleanup-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup registry
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: container
          min-versions-to-keep: ${{ github.event.inputs.min-versions-to-keep }}
          delete-only-untagged-versions: ${{ github.event.inputs.delete-only-untagged-versions }}
