name: Deploy Render

on:
  push:
    branches:
      - 'swift/**'
  workflow_dispatch:

jobs:
  deploy_render:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: https://dashboard.render.com/web/${{ vars.RENDER_SERVICE_ID }}/deploys/${{ steps.trigger-deploy.outputs.id }}
    steps:
      - name: Trigger Deploy
        id: trigger-deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ vars.RENDER_SERVICE_ID }}
        run: |
          test -n "${RENDER_API_KEY}" -a -n "${RENDER_SERVICE_ID}"
          curl --request POST \
          --url https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys \
          --header 'accept: application/json' \
          --header "authorization: Bearer ${RENDER_API_KEY}" \
          --header 'content-type: application/json' \
          --data '{"clearCache": "clear"}'|jq -r '["id",.id]|join("=")' >> $GITHUB_OUTPUT
