name: Update Heroku

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "20 0,3,6,9,12,15,18,21 * * *"
  workflow_dispatch:
    inputs:
      force-update:
        description: Force Update Heroku
        required: false
        default: false

jobs:
  update_heroku:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        id: ['nightly', '5.7', '5.6', '5.5', '5.4', '5.3', '5.2', '5.1', '5.0', '4.2']
        include:
          - id: 'nightly'
            swift_webroot: 'https://download.swift.org/development/ubuntu2004'
          - id: '5.7'
            swift_webroot: 'https://download.swift.org/swift-5.7-branch/ubuntu2004'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Using default '1' causes creating detached branch on Forrce Push Commit.
          ref: swift/${{ matrix.id }}

      - name: Check Commit
        if: ${{ !github.event.inputs.force-update }}
        id: check-commit
        run: |
          timestamp=$(git show -s --format=%ct) &&
          echo "timestamp=${timestamp}" >> $GITHUB_OUTPUT

      - name: Check Docker Image
        if: ${{ !github.event.inputs.force-update && !startsWith(matrix.swift_webroot, 'https:') }}
        id: check-image
        env:
          ID: ${{ matrix.id }}
          REPOSITORY: ${{ matrix.repository }}
          TAG: ${{ matrix.tag }}
        run: |
          REPOSITORY=${REPOSITORY:-library/swift}
          TAG=${TAG:-${ID}}
          endpoint="https://hub.docker.com/v2/repositories/${REPOSITORY}/tags/${TAG}"
          tag_last_pushed=$(curl --silent "${endpoint}"|jq -r .tag_last_pushed) &&
          timestamp=$(date -d "${tag_last_pushed}" "+%s") &&
          echo "timestamp=${timestamp}" >> $GITHUB_OUTPUT

      - name: Check Development Snapshots
        if: ${{ !github.event.inputs.force-update && startsWith(matrix.swift_webroot, 'https:') }}
        id: check-snapshot
        run: |
          endpoint="${{ matrix.swift_webroot }}/latest-build.yml"
          latest_build_date=$(curl --silent "${endpoint}"|sed -n '/^date:/s/date: *//p') &&
          timestamp=$(date -d "${latest_build_date}" "+%s") &&
          echo "timestamp=${timestamp}" >> $GITHUB_OUTPUT

      - name: Verify Timestamps
        if: >
          steps.check-commit.outputs.timestamp == null ||
          (steps.check-image.outputs.timestamp == null && steps.check-snapshot.outputs.timestamp == null )
        run: |
          echo "steps.check-commit.outputs.timestamp: ${{ steps.check-commit.outputs.timestamp }}"
          echo "steps.check-image.outputs.timestamp: ${{ steps.check-image.outputs.timestamp }}"
          echo "steps.check-snapshot.outputs.timestamp: ${{ steps.check-snapshot.outputs.timestamp }}"
          false

      - name: Force Push Commit
        if: >
          github.event.inputs.force-update ||
          steps.check-commit.outputs.timestamp < steps.check-image.outputs.timestamp ||
          steps.check-commit.outputs.timestamp < steps.check-snapshot.outputs.timestamp
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit --amend --no-edit
          git push --force
