name: Update Branches

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "20 0,3,6,9,12,15,18,21 * * *"
  workflow_dispatch:
    inputs:
      force-update:
        description: Specify id or `all` to force updating branches
        required: false

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      ids: ${{ steps.query-ids.outputs.ids }}
    steps:
      - name: Query ids
        id: query-ids
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ids=$(
            gh api graphql -F owner=${{ github.repository_owner }} -F name=${{ github.event.repository.name }} --paginate -f query='
              query($owner: String!, $name: String!, $endCursor: String) {
                repository(owner: $owner, name: $name) {
                  refs(refPrefix: "refs/heads/swift/", first: 100, after: $endCursor) {
                    nodes {
                      name
                    }
                    pageInfo {
                      hasNextPage
                      endCursor
                    }
                  }
                }
              }
            ' --jq '[.data.repository.refs.nodes[].name]' | jq -c
          )
          echo "ids=${ids}" >> $GITHUB_OUTPUT

  update_branches:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        id: ${{ fromJSON(needs.prepare-matrix.outputs.ids) }}
        repository: ["library/swift"]
        tag: [""]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Using default '1' causes creating detached branch on Forrce Push Commit.
          ref: swift/${{ matrix.id }}
          # To trigger new workflow run by pushing commit, do not use secrets.GITHUB_TOKEN
          token: ${{ secrets.TOKEN_TO_TRIGGER_PUSH_EVENTS }}

      - name: Check Commit
        if: ${{ !inputs.force-update }}
        id: check-commit
        run: |
          timestamp=$(git show -s --format=%ct) &&
          echo "timestamp=${timestamp}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Parse Docker Compose
        id: build-args
        run: |
          touch .github_token # Ensure the file exists for the build context
          echo "platform_webroot=$(docker buildx bake --progress=quiet --call outline|awk '/^PLATFORM_WEBROOT/{print $2}')" >> $GITHUB_OUTPUT

      - name: Check Docker Image
        if: ${{ !inputs.force-update && !startsWith(steps.build-args.outputs.platform_webroot, 'https:') }}
        id: check-image
        env:
          ID: ${{ matrix.id }}
          REPOSITORY: ${{ matrix.repository }}
          TAG: ${{ matrix.tag }}
        run: |
          REPOSITORY=${REPOSITORY:-library/swift}
          TAG=${TAG:-${ID}}
          endpoint="https://hub.docker.com/v2/repositories/${REPOSITORY}/tags/${TAG}"
          tag_last_pushed=$(curl --silent "${endpoint}"|jq -r .tag_last_pushed) &&
          timestamp=$(date -d "${tag_last_pushed}" "+%s") &&
          echo "timestamp=${timestamp}" >> $GITHUB_OUTPUT

      - name: Check Development Snapshots
        if: ${{ !inputs.force-update && startsWith(steps.build-args.outputs.platform_webroot, 'https:') }}
        id: check-snapshot
        run: |
          endpoint="${{ steps.build-args.outputs.platform_webroot }}/latest-build.yml"
          latest_build_date=$(curl --silent "${endpoint}"|sed -n '/^date:/s/date: *//p') &&
          timestamp=$(date -d "${latest_build_date}" "+%s") &&
          echo "timestamp=${timestamp}" >> $GITHUB_OUTPUT

      - name: Verify Timestamps
        if: >
          !inputs.force-update && (
            steps.check-commit.outputs.timestamp == null ||
            (steps.check-image.outputs.timestamp == null && steps.check-snapshot.outputs.timestamp == null )
          )
        run: |
          echo "steps.check-commit.outputs.timestamp: ${{ steps.check-commit.outputs.timestamp }}"
          echo "steps.check-image.outputs.timestamp: ${{ steps.check-image.outputs.timestamp }}"
          echo "steps.check-snapshot.outputs.timestamp: ${{ steps.check-snapshot.outputs.timestamp }}"
          false

      - name: Update Swift SDKs
        id: update-swift-sdks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          [[ -x ./update-swift-sdks.sh ]] || exit 0 # Some branches may not have the script
          git config user.name github-actions
          git config user.email github-actions@github.com
          ./update-swift-sdks.sh
          git add swift-sdks.txt
          if ! git diff --cached --quiet; then
            commit_message="Update Swift SDKs"
            last_commit_subject=$(git log -1 --pretty=%s)
            [[ "$commit_message" == "$last_commit_subject" ]] || git commit -m "$commit_message"
            echo "updated=true" >> $GITHUB_OUTPUT
          fi

      - name: Force Push Commit
        if: >
          contains(inputs.force-update, 'all') || contains(inputs.force-update, matrix.id)  || steps.check-commit.outputs.timestamp < steps.check-image.outputs.timestamp || steps.check-commit.outputs.timestamp < steps.check-snapshot.outputs.timestamp || steps.update-swift-sdks.outputs.updated == 'true'
        run: |
          git commit --amend --no-edit
          git push --force
